// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export class SupabaseConfigError extends Error {
  constructor(public readonly missing: string[]) {
    super(
      `Missing Supabase environment variable(s): ${missing.join(
        ", ",
      )}. Create a .env.local file in the repository root.`,
    );
    this.name = "SupabaseConfigError";
  }
}

function readProcessEnv(key: string) {
  if (typeof process === "undefined") return undefined;
  return process.env?.[key];
}

function readSupabaseConfig() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    import.meta.env.SUPABASE_URL ||
    readProcessEnv("SUPABASE_URL");

  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    readProcessEnv("SUPABASE_PUBLISHABLE_KEY");

  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

export function getMissingSupabaseClientEnv() {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = readSupabaseConfig();
  return [
    ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
    ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
  ];
}

function createSupabaseClient() {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = readSupabaseConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = getMissingSupabaseClientEnv();
    const error = new SupabaseConfigError(missing);
    console.error(`[Supabase] ${error.message}`);
    throw error;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
